In [61]:
import tensorflow as tf
import numpy as np

In [19]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [47]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [48]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [45]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    if step % 20 == 0:
        print(step, "cost: ",cost_val, "\nprediction: \n", hy_val)

0 cost:  47881.523 
prediction: 
 [[-53.362362]
 [-63.044724]
 [-62.89685 ]
 [-66.31003 ]
 [-49.538612]
 [-32.860504]
 [-46.564217]
 [-30.295038]
 [-55.9096  ]
 [-46.741573]
 [-46.784042]
 [-44.75801 ]
 [-67.25317 ]
 [-58.9507  ]
 [-46.359756]
 [-61.96907 ]
 [-58.464207]
 [-54.820213]
 [-64.63236 ]
 [-57.514214]
 [-55.29097 ]
 [-57.02484 ]
 [-53.431435]
 [-59.053745]
 [-66.584816]]
20 cost:  8.828011 
prediction: 
 [[152.36005 ]
 [184.20462 ]
 [180.7277  ]
 [199.00835 ]
 [139.03278 ]
 [106.153114]
 [152.02788 ]
 [116.91821 ]
 [175.15132 ]
 [167.26009 ]
 [144.55363 ]
 [143.89777 ]
 [184.45197 ]
 [150.29967 ]
 [153.1429  ]
 [188.92487 ]
 [140.82498 ]
 [183.50745 ]
 [175.33519 ]
 [157.19931 ]
 [177.59093 ]
 [174.92175 ]
 [168.60603 ]
 [148.38051 ]
 [189.66554 ]]
40 cost:  8.78738 
prediction: 
 [[152.37805 ]
 [184.216   ]
 [180.74481 ]
 [199.01999 ]
 [139.04468 ]
 [106.1499  ]
 [152.02908 ]
 [116.908905]
 [175.15106 ]
 [167.24352 ]
 [144.55891 ]
 [143.89575 ]
 [184.4766  ]
 [150.32944 ]
 

540 cost:  7.9602447 
prediction: 
 [[152.55652 ]
 [184.21182 ]
 [180.86638 ]
 [198.99535 ]
 [139.11644 ]
 [105.934425]
 [151.83803 ]
 [116.532524]
 [174.90427 ]
 [166.64786 ]
 [144.47095 ]
 [143.65215 ]
 [184.7595  ]
 [150.77469 ]
 [152.89977 ]
 [188.79686 ]
 [141.4056  ]
 [183.22923 ]
 [175.68973 ]
 [157.5114  ]
 [177.39403 ]
 [174.78279 ]
 [168.48448 ]
 [148.9611  ]
 [189.78648 ]]
560 cost:  7.9335413 
prediction: 
 [[152.56271]
 [184.21188]
 [180.8707 ]
 [198.99442]
 [139.1193 ]
 [105.92694]
 [151.831  ]
 [116.51868]
 [174.89569]
 [166.62677]
 [144.46776]
 [143.64357]
 [184.76964]
 [150.7907 ]
 [152.89098]
 [188.79222]
 [141.4254 ]
 [183.21895]
 [175.70143]
 [157.52164]
 [177.38673]
 [174.7778 ]
 [168.47977]
 [148.98053]
 [189.79037]]
580 cost:  7.907265 
prediction: 
 [[152.56883]
 [184.21194]
 [180.87498]
 [198.99348]
 [139.12215]
 [105.91952]
 [151.824  ]
 [116.50491]
 [174.88722]
 [166.60588]
 [144.4646 ]
 [143.63509]
 [184.77968]
 [150.80656]
 [152.88225]
 [188.78761]
 [141.44

1080 cost:  7.3689985 
prediction: 
 [[152.70174]
 [184.21764]
 [180.97044]
 [198.97128]
 [139.19206]
 [105.75787]
 [151.66254]
 [116.18739]
 [174.70236]
 [166.14162]
 [144.39272]
 [143.44768]
 [185.00513]
 [151.16425]
 [152.683  ]
 [188.68724]
 [141.89119]
 [182.97112]
 [175.97176]
 [157.75691]
 [177.21313]
 [174.66466]
 [168.36552]
 [149.42891]
 [189.884  ]]
1100 cost:  7.35155 
prediction: 
 [[152.70634]
 [184.21802]
 [180.97385]
 [198.97044]
 [139.19481]
 [105.75227]
 [151.65659]
 [116.1757 ]
 [174.69597]
 [166.12518]
 [144.39012]
 [143.4411 ]
 [185.01321]
 [151.17711]
 [152.67575]
 [188.68378]
 [141.90736]
 [182.9623 ]
 [175.98096]
 [157.7649 ]
 [177.20705]
 [174.66089]
 [168.36145]
 [149.44415]
 [189.88736]]
1120 cost:  7.3343716 
prediction: 
 [[152.71086 ]
 [184.2184  ]
 [180.97719 ]
 [198.96959 ]
 [139.19756 ]
 [105.746735]
 [151.65065 ]
 [116.16406 ]
 [174.68964 ]
 [166.1089  ]
 [144.38753 ]
 [143.43457 ]
 [185.02121 ]
 [151.18987 ]
 [152.66855 ]
 [188.68033 ]
 [141.92342 ]
 

1660 cost:  6.9582505 
prediction: 
 [[152.81557 ]
 [184.2319  ]
 [181.05745 ]
 [198.94814 ]
 [139.2695  ]
 [105.618164]
 [151.5038  ]
 [115.87576 ]
 [174.54292 ]
 [165.72197 ]
 [144.32436 ]
 [143.2808  ]
 [185.21394 ]
 [151.49834 ]
 [152.49214 ]
 [188.60054 ]
 [142.31462 ]
 [182.73473 ]
 [176.20842 ]
 [157.9604  ]
 [177.05159 ]
 [174.57051 ]
 [168.25551 ]
 [149.8202  ]
 [189.97383 ]]
1680 cost:  6.94708 
prediction: 
 [[152.81885]
 [184.23251]
 [181.06006]
 [198.94739]
 [139.2721 ]
 [105.61411]
 [151.49881]
 [115.86598]
 [174.5383 ]
 [165.70943]
 [144.32225]
 [143.27588]
 [185.22028]
 [151.50854]
 [152.48624]
 [188.59804]
 [142.32767]
 [182.72723]
 [176.21558]
 [157.96649]
 [177.04655]
 [174.56778]
 [168.25203]
 [149.83197]
 [189.97668]]
1700 cost:  6.936096 
prediction: 
 [[152.8221 ]
 [184.23311]
 [181.06264]
 [198.94664]
 [139.27467]
 [105.61009]
 [151.49385]
 [115.85625]
 [174.53372]
 [165.69699]
 [144.32014]
 [143.27097]
 [185.22655]
 [151.51866]
 [152.48036]
 [188.59554]
 [142.3

In [ ]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv', 'data-01-test-score.csv', ...], shuffle=False, name='filename_queue')
# 파일 여러개는 이렇게 합친다.

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)


train_x_batch, train_y_batch = tf.train.batch(xy[0:-1], xy[-1:]], batch_size=10)
# slicing 방식이 일반적인 것과 다름에 유의 (row 신경쓰지 않고 col만 적는 듯)

sess = tf.Session()
...

# thread를 나눠서 따로따로 돌린 후
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    ...
    

# 합쳐준다.
coord.request_stop(
coord.join(threads)

In [50]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  1583.6143 
Prediction:
 [[116.00015 ]
 [143.92259 ]
 [139.72237 ]
 [149.43834 ]
 [113.117035]
 [ 79.67071 ]
 [106.504776]
 [ 71.345604]
 [132.19347 ]
 [116.78337 ]]
10 Cost:  48.08938 
Prediction:
 [[152.97614 ]
 [188.37761 ]
 [183.51645 ]
 [197.14961 ]
 [147.0112  ]
 [104.68605 ]
 [142.23868 ]
 [ 97.864624]
 [173.76276 ]
 [155.32364 ]]
20 Cost:  47.300716 
Prediction:
 [[153.21716 ]
 [188.67345 ]
 [183.80354 ]
 [197.477   ]
 [147.22624 ]
 [104.867966]
 [142.50385 ]
 [ 98.089165]
 [174.0586  ]
 [155.63068 ]]
30 Cost:  47.016327 
Prediction:
 [[153.21037]
 [188.6713 ]
 [183.79712]
 [197.48462]
 [147.21402]
 [104.88223]
 [142.52963]
 [ 98.13614]
 [174.07584]
 [155.67952]]
40 Cost:  46.737022 
Prediction:
 [[153.20197]
 [188.66711]
 [183.78877]
 [197.49007]
 [147.2003 ]
 [104.89527]
 [142.55371]
 [ 98.18177]
 [174.0911 ]
 [155.72638]]
50 Cost:  46.459766 
Prediction:
 [[153.19359]
 [188.66289]
 [183.78038]
 [197.49547]
 [147.18655]
 [104.90822]
 [142.57768]
 [ 98.22726]
 [174.106

520 Cost:  35.468246 
Prediction:
 [[152.8646 ]
 [188.4538 ]
 [183.42735]
 [197.73184]
 [146.56116]
 [105.42748]
 [143.62636]
 [100.21774]
 [174.71301]
 [157.72466]]
530 Cost:  35.272408 
Prediction:
 [[152.85883 ]
 [188.44916 ]
 [183.42061 ]
 [197.73653 ]
 [146.5483  ]
 [105.4368  ]
 [143.64708 ]
 [100.257126]
 [174.72388 ]
 [157.76147 ]]
540 Cost:  35.07795 
Prediction:
 [[152.8531 ]
 [188.4445 ]
 [183.41388]
 [197.74118]
 [146.53543]
 [105.44603]
 [143.66772]
 [100.29638]
 [174.73466]
 [157.79811]]
550 Cost:  34.88486 
Prediction:
 [[152.84746]
 [188.43987]
 [183.40723]
 [197.74582]
 [146.5226 ]
 [105.45522]
 [143.68834]
 [100.33553]
 [174.74539]
 [157.83456]]
560 Cost:  34.69315 
Prediction:
 [[152.84181 ]
 [188.4352  ]
 [183.40056 ]
 [197.75044 ]
 [146.50975 ]
 [105.464325]
 [143.70886 ]
 [100.37454 ]
 [174.756   ]
 [157.87083 ]]
570 Cost:  34.502815 
Prediction:
 [[152.83626]
 [188.43054]
 [183.39397]
 [197.75508]
 [146.49698]
 [105.47338]
 [143.72934]
 [100.41345]
 [174.7666 ]
 

1050 Cost:  26.764334 
Prediction:
 [[152.61841 ]
 [188.20175 ]
 [183.10909 ]
 [197.96132 ]
 [145.90456 ]
 [105.837845]
 [144.64308 ]
 [102.151405]
 [175.19177 ]
 [159.44585 ]]
1060 Cost:  26.628733 
Prediction:
 [[152.6148 ]
 [188.19691]
 [183.10378]
 [197.9653 ]
 [145.89267]
 [105.84409]
 [144.66075]
 [102.18504]
 [175.19907]
 [159.47415]]
1070 Cost:  26.493988 
Prediction:
 [[152.61124]
 [188.19208]
 [183.09848]
 [197.96928]
 [145.8808 ]
 [105.85031]
 [144.67839]
 [102.2186 ]
 [175.2063 ]
 [159.50233]]
1080 Cost:  26.36022 
Prediction:
 [[152.60771]
 [188.18723]
 [183.09323]
 [197.97325]
 [145.86897]
 [105.85647]
 [144.69594]
 [102.25204]
 [175.2135 ]
 [159.5304 ]]
1090 Cost:  26.2273 
Prediction:
 [[152.60419 ]
 [188.18237 ]
 [183.08798 ]
 [197.9772  ]
 [145.85712 ]
 [105.862595]
 [144.71346 ]
 [102.28539 ]
 [175.22063 ]
 [159.55827 ]]
1100 Cost:  26.095282 
Prediction:
 [[152.60074]
 [188.17752]
 [183.08276]
 [197.98116]
 [145.84532]
 [105.86866]
 [144.73093]
 [102.31864]
 [175.22

1580 Cost:  20.689661 
Prediction:
 [[152.47087]
 [187.9442 ]
 [182.85812]
 [198.15744]
 [145.3008 ]
 [106.10805]
 [145.51102]
 [103.80532]
 [175.50627]
 [160.76804]]
1590 Cost:  20.594166 
Prediction:
 [[152.46886]
 [187.93933]
 [182.85393]
 [198.16086]
 [145.28993]
 [106.11205]
 [145.52614]
 [103.83412]
 [175.51093]
 [160.78976]]
1600 Cost:  20.499279 
Prediction:
 [[152.46686 ]
 [187.93448 ]
 [182.84976 ]
 [198.16426 ]
 [145.27907 ]
 [106.11602 ]
 [145.54118 ]
 [103.862854]
 [175.51552 ]
 [160.81137 ]]
1610 Cost:  20.405037 
Prediction:
 [[152.4649 ]
 [187.92966]
 [182.84563]
 [198.16766]
 [145.26822]
 [106.11995]
 [145.55621]
 [103.89149]
 [175.5201 ]
 [160.83289]]
1620 Cost:  20.311337 
Prediction:
 [[152.46295]
 [187.92479]
 [182.84148]
 [198.17105]
 [145.25739]
 [106.12385]
 [145.57117]
 [103.92005]
 [175.5246 ]
 [160.8543 ]]
1630 Cost:  20.21828 
Prediction:
 [[152.46103 ]
 [187.91995 ]
 [182.83737 ]
 [198.17442 ]
 [145.24658 ]
 [106.1277  ]
 [145.5861  ]
 [103.948524]
 [175.52