In [1]:
import tensorflow as tf
tf.set_random_seed(777)

In [8]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)


Tensor("add_11:0", dtype=float32)
0 Cost:  6854.0444 
Prediction
 [ 83.55517   92.5179    95.20042  105.433876  66.904076]
10 Cost:  24.916027 
Prediction
 [156.64021 180.3948  181.76935 199.70651 133.93948]
20 Cost:  24.732052 
Prediction
 [156.84341 180.67308 182.02586 199.9871  134.1592 ]
30 Cost:  24.611307 
Prediction
 [156.82614 180.68626 182.02127 199.9833  134.17668]
40 Cost:  24.491264 
Prediction
 [156.80824 180.6986  182.01587 199.97867 134.1935 ]
50 Cost:  24.371801 
Prediction
 [156.79039 180.7109  182.0105  199.97404 134.21028]
60 Cost:  24.252918 
Prediction
 [156.77258 180.72318 182.00513 199.96939 134.22702]
70 Cost:  24.134752 
Prediction
 [156.75485 180.73544 181.9998  199.96481 134.24373]
80 Cost:  24.017262 
Prediction
 [156.73714 180.74763 181.99446 199.96022 134.26036]
90 Cost:  23.90034 
Prediction
 [156.7195  180.75983 181.98917 199.95564 134.27698]
100 Cost:  23.784042 
Prediction
 [156.70189 180.77197 181.98386 199.95107 134.29353]
110 Cost:  23.66838 
Predic

1080 Cost:  14.943344 
Prediction
 [155.19255 181.81393 181.53062 199.55135 135.72159]
1090 Cost:  14.874931 
Prediction
 [155.17917 181.82318 181.52661 199.54773 135.73434]
1100 Cost:  14.806864 
Prediction
 [155.1658  181.83241 181.52261 199.54411 135.74706]
1110 Cost:  14.739133 
Prediction
 [155.1525  181.84161 181.51862 199.5405  135.75975]
1120 Cost:  14.6718235 
Prediction
 [155.13922 181.85078 181.51466 199.5369  135.7724 ]
1130 Cost:  14.6048 
Prediction
 [155.12598 181.85995 181.5107  199.53333 135.78503]
1140 Cost:  14.538211 
Prediction
 [155.11278 181.86908 181.50674 199.52974 135.7976 ]
1150 Cost:  14.471914 
Prediction
 [155.09961 181.87817 181.50279 199.52615 135.81017]
1160 Cost:  14.406004 
Prediction
 [155.08646 181.88724 181.49887 199.52258 135.82268]
1170 Cost:  14.340403 
Prediction
 [155.07338 181.89632 181.49495 199.51903 135.83517]
1180 Cost:  14.275233 
Prediction
 [155.06033 181.90533 181.49104 199.51549 135.84763]
1190 Cost:  14.210329 
Prediction
 [155.0472

In [7]:
# Matrix !!!

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
print(hypothesis)

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                    feed_dict = {X: x_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction\n", hy_val)


Tensor("add_8:0", shape=(?, 1), dtype=float32)
0 Cost:  83882.766 
Prediction
 [[-103.36177 ]
 [-125.93644 ]
 [-123.263985]
 [-132.45103 ]
 [ -98.15331 ]]
10 Cost:  8.263563 
Prediction
 [[152.82521]
 [181.99783]
 [180.14032]
 [197.94894]
 [136.72688]]
20 Cost:  7.4655395 
Prediction
 [[153.59161]
 [182.93556]
 [181.05573]
 [198.94608]
 [137.44603]]
30 Cost:  7.4354315 
Prediction
 [[153.58524]
 [182.94446]
 [181.05591]
 [198.94656]
 [137.45668]]
40 Cost:  7.4055567 
Prediction
 [[153.57652]
 [182.95047]
 [181.05333]
 [198.94405]
 [137.46515]]
50 Cost:  7.3758492 
Prediction
 [[153.56786]
 [182.9565 ]
 [181.05075]
 [198.94154]
 [137.47359]]
60 Cost:  7.3462496 
Prediction
 [[153.55919]
 [182.96248]
 [181.04817]
 [198.93901]
 [137.48201]]
70 Cost:  7.3168373 
Prediction
 [[153.55057]
 [182.96848]
 [181.04562]
 [198.93652]
 [137.49042]]
80 Cost:  7.2875466 
Prediction
 [[153.54196]
 [182.97444]
 [181.04308]
 [198.93402]
 [137.49881]]
90 Cost:  7.258409 
Prediction
 [[153.53337]
 [182.980

1000 Cost:  5.156404 
Prediction
 [[152.84499]
 [183.45828]
 [180.83717]
 [198.72554]
 [138.18402]]
1010 Cost:  5.1384134 
Prediction
 [[152.83835]
 [183.46288]
 [180.83522]
 [198.72348]
 [138.1906 ]]
1020 Cost:  5.1204963 
Prediction
 [[152.83176]
 [183.46748]
 [180.83328]
 [198.72144]
 [138.19717]]
1030 Cost:  5.102658 
Prediction
 [[152.82515]
 [183.47206]
 [180.83133]
 [198.71939]
 [138.20374]]
1040 Cost:  5.084943 
Prediction
 [[152.81859]
 [183.47665]
 [180.82942]
 [198.71738]
 [138.21028]]
1050 Cost:  5.0673103 
Prediction
 [[152.81201]
 [183.48119]
 [180.82747]
 [198.71532]
 [138.21678]]
1060 Cost:  5.0497603 
Prediction
 [[152.8055 ]
 [183.48576]
 [180.82559]
 [198.71332]
 [138.22331]]
1070 Cost:  5.0323324 
Prediction
 [[152.79895]
 [183.49026]
 [180.82364]
 [198.71127]
 [138.22977]]
1080 Cost:  5.0149565 
Prediction
 [[152.79248]
 [183.4948 ]
 [180.82175]
 [198.70927]
 [138.23627]]
1090 Cost:  4.9976754 
Prediction
 [[152.78598]
 [183.49928]
 [180.81982]
 [198.70723]
 [138.2