In [5]:
import tensorflow as tf
import numpy as np

In [2]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

n_class = 3

X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,n_class])

W = tf.Variable(tf.random_normal([4,n_class]), name='weight')
b = tf.Variable(tf.random_normal([n_class]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
             
    for step in range(2001):
        sess.run(train, feed_dict={X:x_data, Y: y_data})

        if step % 200 == 0:
            print(step, sess.run(cost ,feed_dict={X:x_data, Y:y_data}))
            
            
    # Test
    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 4.4929533
200 0.6009666
400 0.48667645
600 0.3921691
800 0.3010169
1000 0.23942538
1200 0.21683392
1400 0.19802913
1600 0.18211785
1800 0.16848579
2000 0.15668336
--------------
[[1.1775223e-02 9.8821622e-01 8.5230222e-06]] [1]
--------------
[[0.78739816 0.19507398 0.01752778]] [0]
--------------
[[1.1155478e-08 3.3425947e-04 9.9966574e-01]] [2]
--------------
[[1.1775223e-02 9.8821622e-01 8.5230222e-06]
 [7.8739828e-01 1.9507392e-01 1.7527781e-02]
 [1.1155478e-08 3.3425947e-04 9.9966574e-01]] [1 0 2]


## Fancy softmax

In [4]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

n_class = 3

X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,n_class])

W = tf.Variable(tf.random_normal([4,n_class]), name='weight')
b = tf.Variable(tf.random_normal([n_class]), name='bias')

logits = tf.matmul(X,W) + b
hypothesis = tf.nn.softmax(logits)

# cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y)
cost = tf.reduce_mean(cost_i)
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
             
    for step in range(2001):
        sess.run(train, feed_dict={X:x_data, Y: y_data})

        if step % 200 == 0:
            print(step, sess.run(cost ,feed_dict={X:x_data, Y:y_data}))
            
            
    # Test
    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

0 2.8041995
200 0.53244454
400 0.43448156
600 0.35911515
800 0.2863738
1000 0.23205018
1200 0.21012652
1400 0.19191056
1600 0.17652221
1800 0.16335325
2000 0.151961
--------------
[[1.3931872e-03 9.9859637e-01 1.0504310e-05]] [1]
--------------
[[0.9296388  0.06180976 0.00855148]] [0]
--------------
[[1.4588414e-08 3.4211302e-04 9.9965787e-01]] [2]
--------------
[[1.3931872e-03 9.9859637e-01 1.0504320e-05]
 [9.2963880e-01 6.1809760e-02 8.5514812e-03]
 [1.4588414e-08 3.4211302e-04 9.9965787e-01]] [1 0 2]


## Toy dataset: animal classification

In [10]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]
n_class = 7

X = tf.placeholder(tf.float32, shape=[None,16])
Y = tf.placeholder(tf.int32, shape=[None,1])
Y_one_hot = tf.one_hot(Y, n_class) # shape=(?, 1, 7)
Y_one_hot = tf.reshape(Y_one_hot, [-1, n_class]) # shape=(?, 7)

W = tf.Variable(tf.random_normal([16,n_class]), name='weight')
b = tf.Variable(tf.random_normal([n_class]), name='bias')

logits = tf.matmul(X,W) + b
hypothesis = tf.nn.softmax(logits)

# cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
          
    # Training
    for step in range(2001):
        sess.run(train, feed_dict={X:x_data, Y: y_data})

        if step % 200 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={
                                                        X:x_data, Y:y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(
                step, loss, acc))

    # Test    
    pred = sess.run(prediction, feed_dict={X:x_data})

    for p,y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

Step:     0	Loss: 5.422	Acc: 7.92%
Step:   200	Loss: 0.428	Acc: 85.15%
Step:   400	Loss: 0.267	Acc: 91.09%
Step:   600	Loss: 0.189	Acc: 96.04%
Step:   800	Loss: 0.142	Acc: 96.04%
Step:  1000	Loss: 0.113	Acc: 97.03%
Step:  1200	Loss: 0.093	Acc: 99.01%
Step:  1400	Loss: 0.079	Acc: 100.00%
Step:  1600	Loss: 0.068	Acc: 100.00%
Step:  1800	Loss: 0.060	Acc: 100.00%
Step:  2000	Loss: 0.054	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Predi

In [17]:
print(y_data.shape, y_data)
print(y_data.flatten().shape, y_data.flatten())
print(pred.shape)

(101, 1) [[0.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [3.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [6.]
 [6.]
 [6.]
 [1.]
 [0.]
 [3.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [5.]
 [4.]
 [4.]
 [0.]
 [0.]
 [0.]
 [5.]
 [0.]
 [0.]
 [1.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [5.]
 [5.]
 [1.]
 [5.]
 [1.]
 [0.]
 [0.]
 [6.]
 [0.]
 [0.]
 [0.]
 [0.]
 [5.]
 [4.]
 [6.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [3.]
 [3.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [6.]
 [3.]
 [0.]
 [0.]
 [2.]
 [6.]
 [1.]
 [1.]
 [2.]
 [6.]
 [3.]
 [1.]
 [0.]
 [6.]
 [3.]
 [1.]
 [5.]
 [4.]
 [2.]
 [2.]
 [3.]
 [0.]
 [0.]
 [1.]
 [0.]
 [5.]
 [0.]
 [6.]
 [1.]]
(101,) [0. 0. 3. 0. 0. 0. 0. 3. 3. 0. 0. 1. 3. 6. 6. 6. 1. 0. 3. 0. 1. 1. 0. 1.
 5. 4. 4. 0. 0. 0. 5. 0. 0. 1. 3. 0. 0. 1. 3. 5. 5. 1. 5. 1. 0. 0. 6. 0.
 0. 0. 0. 5. 4. 6. 0. 0. 1. 1. 1. 1. 3. 3. 2. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 6. 3. 0. 0. 2. 6. 1. 1. 2. 6. 3. 1. 0. 6. 3. 1. 5. 4. 2. 2. 3. 0. 0. 1.
 0. 5. 0. 6. 1.]
(101,)
